### ISSUE TITLE
Can't able to create database in v8 with this module.

### ISSUE THREAD

**Issue by Chandresh-SerpentCS** [loxamir/sincronizador#2]
Hello @loxamir,

I have cloned your repository in my system and just put your "connector_sincronizador" module in my odoo v8 add-ons directory.

I have gone through all the steps which you mentioned in your repository.

But I can't create even the new v8 database.

If I remove the module from the add-ons, then it allows me to create the database.

Can you please give me the proper guidance to install the module?

**Detailed Traceback:**

Traceback (most recent call last):
  File "/home/serpentcs/workspace/odoo/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/serpentcs/workspace/odoo/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/home/serpentcs/workspace/odoo/openerp/http.py", line 320, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/home/serpentcs/workspace/odoo/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/home/serpentcs/workspace/odoo/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/home/serpentcs/workspace/odoo/addons/web/controllers/main.py", line 705, in create
    request.session.authenticate(params['db_name'], 'admin', params['create_admin_pwd'])
  File "/home/serpentcs/workspace/odoo/openerp/http.py", line 965, in authenticate
    uid = dispatch_rpc('common', 'authenticate', [db, login, password, env])
  File "/home/serpentcs/workspace/odoo/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/serpentcs/workspace/odoo/openerp/service/common.py", line 26, in dispatch
    return fn(*params)
  File "/home/serpentcs/workspace/odoo/openerp/service/common.py", line 37, in exp_authenticate
    res_users = openerp.registry(db)['res.users']
  File "/home/serpentcs/workspace/odoo/openerp/__init__.py", line 68, in registry
    return modules.registry.RegistryManager.get(database_name)
  File "/home/serpentcs/workspace/odoo/openerp/modules/registry.py", line 339, in get
    update_module)
  File "/home/serpentcs/workspace/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/serpentcs/workspace/odoo/openerp/modules/loading.py", line 297, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/home/serpentcs/workspace/odoo/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/home/serpentcs/workspace/odoo/openerp/modules/module.py", line 290, in init_module_models
    obj.init(cr)
  File "/home/serpentcs/workspace/odoo/openerp/tools/misc.py", line 1156, in deco
    return func(*args, **kwargs)
  File "/home/serpentcs/workspace/odoo/openerp/addons/base/ir/ir_config_parameter.py", line 72, in init
    self.set_param(cr, SUPERUSER_ID, key, value, groups=groups)
  File "/home/serpentcs/workspace/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/workspace/odoo/openerp/addons/base/ir/ir_config_parameter.py", line 120, in set_param
    self.create(cr, uid, vals, context=context)
  File "/home/serpentcs/workspace/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/serpentcs/workspace/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/serpentcs/workspace/odoo/addons/connector_sincronizador/models/models.py", line 35, in create_couch
    if module and module.state == 'installed':
  File "/home/serpentcs/workspace/odoo/openerp/fields.py", line 835, in __get__
    self.determine_value(record)
  File "/home/serpentcs/workspace/odoo/openerp/fields.py", line 928, in determine_value
    record._prefetch_field(self)
  File "/home/serpentcs/workspace/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/serpentcs/workspace/odoo/openerp/models.py", line 3246, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/home/serpentcs/workspace/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/serpentcs/workspace/odoo/openerp/models.py", line 3183, in read
    self._read_from_database(stored, inherited)
  File "/home/serpentcs/workspace/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/serpentcs/workspace/odoo/openerp/models.py", line 3315, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/home/serpentcs/workspace/odoo/openerp/sql_db.py", line 171, in wrapper
    return f(self, *args, **kwargs)
  File "/home/serpentcs/workspace/odoo/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column ir_module_module.menus_by_module does not exist
LINE 1:  SELECT "ir_module_module"."summary","ir_module_module"."men...
                                             ^

**Comment by loxamir** [comment]
Hi @Chandresh-SerpentCS!
I have to solve issue #1 after that I will make a video showing how to install and use this module
If you have any Idea how to solve the issue #1 please let me know
thanks for you interest in this module
